// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package openapi provides automated OpenAPI 3.1.0 document generation, DTO reflection, and interactive Scalar UI for sein.
package openapi

import (
	"context"
	"fmt"
	"os"
	"reflect"
	"strings"
	"time"

	"github.com/lemon4ksan/foundation/codec/json"
	"github.com/lemon4ksan/foundation/net/http/header"
	"github.com/lemon4ksan/sein"
)

// Document represents an OpenAPI 3.1.0 root document conforming to https://spec.openapis.org/oas/v3.1.0.
type Document struct {
	OpenAPI    string                          `json:"openapi"`
	Info       Info                            `json:"info"`
	Paths      map[string]map[string]Operation `json:"paths"`
	Components *Components                     `json:"components,omitempty"`
}

// Components holds reusable schemas and parameters for OpenAPI 3.1.
type Components struct {
	Schemas map[string]*Schema `json:"schemas,omitempty"`
}

// Info provides metadata about the API.
type Info struct {
	Title       string `json:"title"`
	Version     string `json:"version"`
	Description string `json:"description,omitempty"`
}

// Operation describes a single API operation on a path.
type Operation struct {
	Summary     string              `json:"summary,omitempty"`
	Description string              `json:"description,omitempty"`
	Parameters  []Parameter         `json:"parameters,omitempty"`
	RequestBody *RequestBody        `json:"requestBody,omitempty"`
	Responses   map[string]Response `json:"responses"`
}

// Parameter describes a single operation parameter (path, query, header, cookie).
type Parameter struct {
	Name        string  `json:"name"`
	In          string  `json:"in"` // "path", "query", "header", "cookie"
	Required    bool    `json:"required"`
	Description string  `json:"description,omitempty"`
	Schema      *Schema `json:"schema,omitempty"`
}

// RequestBody describes a request payload.
type RequestBody struct {
	Description string               `json:"description,omitempty"`
	Required    bool                 `json:"required,omitempty"`
	Content     map[string]MediaType `json:"content"`
}

// MediaType describes a payload content-type schema.
type MediaType struct {
	Schema *Schema `json:"schema,omitempty"`
}

// Response describes an expected HTTP response.
type Response struct {
	Description string               `json:"description"`
	Content     map[string]MediaType `json:"content,omitempty"`
}

// Schema describes a data type schema in OpenAPI 3.1.
type Schema struct {
	Ref         string             `json:"$ref,omitempty"`
	Type        string             `json:"type,omitempty"`
	Title       string             `json:"title,omitempty"`
	Format      string             `json:"format,omitempty"`
	Description string             `json:"description,omitempty"`
	Items       *Schema            `json:"items,omitempty"`
	Properties  map[string]*Schema `json:"properties,omitempty"`
	Required    []string           `json:"required,omitempty"`
}

// ProblemDetailsSchema is the canonical RFC 9457 / sein Problem Details error structure schema.
var ProblemDetailsSchema = &Schema{
	Type:        "object",
	Title:       "ProblemDetails",
	Description: "RFC 9457 standard HTTP Problem Details error response format",
	Properties: map[string]*Schema{
		"status": {
			Type:        "integer",
			Description: "The HTTP status code generated by the origin server",
		},
		"code": {
			Type:        "string",
			Description: "A machine-readable domain error code or error identifier",
		},
		"message": {
			Type:        "string",
			Description: "A human-readable explanation specific to this occurrence of the problem",
		},
		"details": {
			Type:        "object",
			Description: "Optional additional contextual metadata or validation error details",
		},
	},
	Required: []string{"status", "code", "message"},
}

var timeType = reflect.TypeFor[time.Time]()

func schemaFromType(t reflect.Type) *Schema {
	if t == nil {
		return nil
	}

	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}

	if t == timeType {
		return &Schema{Type: "string", Format: "date-time"}
	}

	switch t.Kind() {
	case reflect.Bool:
		return &Schema{Type: "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return &Schema{Type: "integer"}
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return &Schema{Type: "integer"}
	case reflect.Float32, reflect.Float64:
		return &Schema{Type: "number"}
	case reflect.String:
		return &Schema{Type: "string"}
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 {
			return &Schema{Type: "string", Format: "byte"}
		}
		return &Schema{Type: "array", Items: schemaFromType(t.Elem())}
	case reflect.Map:
		return &Schema{Type: "object"}
	case reflect.Struct:
		s := &Schema{
			Type:       "object",
			Properties: make(map[string]*Schema),
		}
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			if !f.IsExported() {
				continue
			}
			jsonTag := f.Tag.Get("json")
			if jsonTag == "-" {
				continue
			}
			name := f.Name
			if jsonTag != "" {
				parts := strings.Split(jsonTag, ",")
				if parts[0] != "" {
					name = parts[0]
				}
			}
			s.Properties[name] = schemaFromType(f.Type)
			validateTag := f.Tag.Get("validate")
			if strings.Contains(validateTag, "required") || strings.Contains(jsonTag, "required") {
				s.Required = append(s.Required, name)
			}
		}
		return s
	default:
		return &Schema{Type: "string"}
	}
}

// Generate builds an OpenAPI 3.1.0 Document from all routes registered on the sein server.
func Generate(s *sein.Server, title, version string) *Document {
	doc := &Document{
		OpenAPI: "3.1.0",
		Info: Info{
			Title:   title,
			Version: version,
		},
		Paths: make(map[string]map[string]Operation),
		Components: &Components{
			Schemas: map[string]*Schema{
				"ProblemDetails": ProblemDetailsSchema,
			},
		},
	}

	routes := s.Routes()
	for _, r := range routes {
		openAPIPath, pathParams := convertRouteToOpenAPI(r.Path)

		if doc.Paths[openAPIPath] == nil {
			doc.Paths[openAPIPath] = make(map[string]Operation)
		}

		op := buildOperation(r, pathParams)
		methodKey := strings.ToLower(r.Method)
		doc.Paths[openAPIPath][methodKey] = op
	}

	return doc
}

func buildOperation(r sein.RouteInfo, pathParams []Parameter) Operation {
	params := append([]Parameter{}, pathParams...)
	var reqBody *RequestBody

	problemMedia := map[string]MediaType{
		"application/problem+json": {
			Schema: &Schema{Ref: "#/components/schemas/ProblemDetails"},
		},
		"application/json": {
			Schema: &Schema{Ref: "#/components/schemas/ProblemDetails"},
		},
	}

	responses := map[string]Response{
		"200": {Description: "Successful operation"},
		"400": {Description: "Bad Request - invalid query, header, or payload structure", Content: problemMedia},
		"401": {Description: "Unauthorized - missing or invalid authentication credentials", Content: problemMedia},
		"403": {Description: "Forbidden - authenticated caller does not have sufficient permissions", Content: problemMedia},
		"404": {Description: "Not Found - requested resource or route does not exist", Content: problemMedia},
		"500": {Description: "Internal Server Error - an unexpected error occurred on the server", Content: problemMedia},
	}

	if r.HandlerType != nil {
		ht := r.HandlerType
		numIn := ht.NumIn()
		for i := 0; i < numIn; i++ {
			inType := ht.In(i)
			for inType.Kind() == reflect.Pointer {
				inType = inType.Elem()
			}
			// Skip context and *sein.Request
			if inType.Implements(reflect.TypeFor[context.Context]()) || inType.String() == "sein.Request" {
				continue
			}
			if inType.Kind() == reflect.Struct {
				var bodyProps map[string]*Schema
				var bodyReq []string

				for j := 0; j < inType.NumField(); j++ {
					f := inType.Field(j)
					if !f.IsExported() {
						continue
					}
					if qTag := f.Tag.Get("query"); qTag != "" {
						qName := parseTagName(qTag, f.Name)
						params = append(params, Parameter{
							Name:     qName,
							In:       "query",
							Required: strings.Contains(qTag, "required"),
							Schema:   schemaFromType(f.Type),
						})
					} else if hTag := f.Tag.Get("header"); hTag != "" {
						hName := parseTagName(hTag, f.Name)
						params = append(params, Parameter{
							Name:     hName,
							In:       "header",
							Required: strings.Contains(hTag, "required"),
							Schema:   schemaFromType(f.Type),
						})
					} else if cTag := f.Tag.Get("cookie"); cTag != "" {
						cName := parseTagName(cTag, f.Name)
						params = append(params, Parameter{
							Name:     cName,
							In:       "cookie",
							Required: strings.Contains(cTag, "required"),
							Schema:   schemaFromType(f.Type),
						})
					} else {
						// JSON Body field
						jsonTag := f.Tag.Get("json")
						if jsonTag != "-" {
							if bodyProps == nil {
								bodyProps = make(map[string]*Schema)
							}
							jName := parseTagName(jsonTag, f.Name)
							bodyProps[jName] = schemaFromType(f.Type)
							if strings.Contains(f.Tag.Get("validate"), "required") || strings.Contains(jsonTag, "required") {
								bodyReq = append(bodyReq, jName)
							}
						}
					}
				}

				if len(bodyProps) > 0 && (r.Method == "POST" || r.Method == "PUT" || r.Method == "PATCH") {
					reqBody = &RequestBody{
						Required: true,
						Content: map[string]MediaType{
							"application/json": {
								Schema: &Schema{
									Type:       "object",
									Properties: bodyProps,
									Required:   bodyReq,
								},
							},
						},
					}
				}
			}
		}

		if ht.NumOut() > 0 {
			outType := ht.Out(0)
			for outType.Kind() == reflect.Pointer {
				outType = outType.Elem()
			}
			if !outType.Implements(reflect.TypeFor[error]()) && outType.Kind() != reflect.Interface {
				schema := schemaFromType(outType)
				if schema != nil {
					responses["200"] = Response{
						Description: "Successful operation",
						Content: map[string]MediaType{
							"application/json": {
								Schema: schema,
							},
						},
					}
				}
			}
		}
	}

	return Operation{
		Summary:     fmt.Sprintf("%s %s", r.Method, r.Path),
		Parameters:  params,
		RequestBody: reqBody,
		Responses:   responses,
	}
}

func parseTagName(tag, defaultName string) string {
	parts := strings.Split(tag, ",")
	if parts[0] != "" {
		return parts[0]
	}
	return defaultName
}

// ToJSON serializes the document into pretty-printed JSON bytes.
func (d *Document) ToJSON() ([]byte, error) {
	return json.Marshal(d)
}

// Export writes the OpenAPI specification directly to a local JSON file.
func (d *Document) Export(filepath string) error {
	data, err := d.ToJSON()
	if err != nil {
		return err
	}
	return os.WriteFile(filepath, data, 0o600)
}

func convertRouteToOpenAPI(routePath string) (string, []Parameter) {
	var params []Parameter
	segments := strings.Split(routePath, "/")

	for i, seg := range segments {
		if strings.HasPrefix(seg, ":") {
			paramName := strings.TrimPrefix(seg, ":")
			segments[i] = "{" + paramName + "}"
			params = append(params, Parameter{
				Name:     paramName,
				In:       "path",
				Required: true,
				Schema:   &Schema{Type: "string"},
			})
		} else if strings.HasPrefix(seg, "*") {
			paramName := strings.TrimPrefix(seg, "*")
			segments[i] = "{" + paramName + "}"
			params = append(params, Parameter{
				Name:     paramName,
				In:       "path",
				Required: true,
				Schema:   &Schema{Type: "string"},
			})
		}
	}

	return strings.Join(segments, "/"), params
}

// EnableDocs registers automatic OpenAPI spec serving and an interactive Scalar documentation UI on the server.
func EnableDocs(s *sein.Server, mountPath, title, version string) {
	base := strings.TrimSuffix(mountPath, "/")
	specURL := base + "/openapi.json"

	doc := Generate(s, title, version)
	specJSON, _ := doc.ToJSON()

	// Serve raw OpenAPI 3.1 JSON
	s.Get(specURL, func(_ context.Context) (any, error) {
		return sein.OK[any](specJSON).
			WithHeader(header.ContentType, header.MIMEApplicationJSONCharsetUTF8), nil
	})

	// Serve Scalar API Reference UI
	scalarHTML := renderScalarHTML(title, specURL)
	s.Get(base, func(_ context.Context) (any, error) {
		return sein.OK[any](scalarHTML).
			WithHeader(header.ContentType, header.MIMETextHTMLCharsetUTF8), nil
	})
	s.Get(base+"/", func(_ context.Context) (any, error) {
		return sein.OK[any](scalarHTML).
			WithHeader(header.ContentType, header.MIMETextHTMLCharsetUTF8), nil
	})
}

func renderScalarHTML(title, specURL string) string {
	return fmt.Sprintf(`<!doctype html>
<html>
  <head>
    <title>%s</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <script id="api-reference" data-url="%s"></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>`, title, specURL)
}
