// Code generated by c2plan9. DO NOT EDIT.
//go:build amd64 && !purego

package h1

import "unsafe"

var _ = unsafe.Pointer(nil)

//go:noescape
func h1_parse_hex_uint(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64) uint64

//go:noescape
func h1_format_hex_uint(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64) uint64

//go:noescape
func h1_format_chunk_header(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64) uint64
