// Code generated by c2plan9. DO NOT EDIT.

//go:build arm64 && !purego

#include "textflag.h"

// func quic_decode_packet_number
TEXT ·quic_decode_packet_number(SB), NOSPLIT, $0-72
	MOVD arg0+0(FP), R0
	MOVD arg1+8(FP), R1
	MOVD arg2+16(FP), R2
	MOVD arg3+24(FP), R3
	MOVD arg4+32(FP), R4
	MOVD arg5+40(FP), R5
	MOVD arg6+48(FP), R6
	MOVD arg7+56(FP), R7

	LSL $3, R0, R8
	MOVW $1, R9
	LSL R8, R9, R8
	ADD $1, R1, R9
	NEG R8, R10
	LSR $1, R8, R11
	AND R10, R9, R10
	ORR R2, R10, R10
	ADD R9, R11, R12
	SUB R11, R9, R9
	CMP R8, R10
	MOVD $4611686018427387904, R11
	CCMP GE, R10, R12, $4
	SUB R8, R11, R11
	CSEL LE, ZR, R8, R12
	CMP R9, R10
	ADD R8, R10, R8
	SUB R12, R10, R9
	CCMP LE, R10, R11, $0
	CSEL GE, R9, R8, R0
	MOVD R0, ret+64(FP)
	RET

// func quic_packet_number_len_for_header
TEXT ·quic_packet_number_len_for_header(SB), NOSPLIT, $0-72
	MOVD arg0+0(FP), R0
	MOVD arg1+8(FP), R1
	MOVD arg2+16(FP), R2
	MOVD arg3+24(FP), R3
	MOVD arg4+32(FP), R4
	MOVD arg5+40(FP), R5
	MOVD arg6+48(FP), R6
	MOVD arg7+56(FP), R7

	MOVW $1, R8
	CMP $0, R1
	MOVW $3, R9
	CSNEG LT, R8, R1, R8
	ADD R0, R8, R8
	CMP $(2048<<12), R8
	CINC HS, R9, R9
	CMP $(8<<12), R8
	MOVW $2, R8
	CSEL LT, R8, R9, R0
	MOVD R0, ret+64(FP)
	RET

