// Code generated by c2plan9. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func quic_decode_packet_number
TEXT ·quic_decode_packet_number(SB), NOSPLIT, $0-56
	MOVQ arg0+0(FP), DI
	MOVQ arg1+8(FP), SI
	MOVQ arg2+16(FP), DX
	MOVQ arg3+24(FP), CX
	MOVQ arg4+32(FP), R8
	MOVQ arg5+40(FP), R9

	INCQ SI
	LEAL 0(DI*8), CX
	MOVL $0x1, DI
	SHLQ CL, DI
	MOVQ DI, CX
	SHRQ $0x1, CX
	MOVQ DI, AX
	NEGQ AX
	ANDQ SI, AX
	ORQ DX, AX
	MOVQ SI, DX
	SUBQ CX, DX
	CMPQ AX, DX
	SETLE DL
	MOVQ $0x4000000000000000, R8
	SUBQ DI, R8
	CMPQ AX, R8
	SETLT R8B
	ANDB DL, R8B
	CMPB R8B, $0x1
	JNE L_0051
	ADDQ DI, AX
	MOVQ AX, ret+48(FP)
	RET
L_0051:
	ADDQ SI, CX
	XORL DX, DX
	CMPQ AX, DI
	CMOVQLT DX, DI
	CMPQ AX, CX
	CMOVQLE DX, DI
	SUBQ DI, AX
	MOVQ AX, ret+48(FP)
	RET

// func quic_packet_number_len_for_header
TEXT ·quic_packet_number_len_for_header(SB), NOSPLIT, $0-56
	MOVQ arg0+0(FP), DI
	MOVQ arg1+8(FP), SI
	MOVQ arg2+16(FP), DX
	MOVQ arg3+24(FP), CX
	MOVQ arg4+32(FP), R8
	MOVQ arg5+40(FP), R9

	MOVQ SI, AX
	NEGQ AX
	TESTQ SI, SI
	MOVL $0x1, CX
	CMOVQPL AX, CX
	ADDQ DI, CX
	CMPQ CX, $0x800000
	MOVL $0x4, DX
	SBBQ $0x0, DX
	CMPQ CX, $0x8000
	MOVL $0x2, AX
	CMOVQGE DX, AX
	MOVQ AX, ret+48(FP)
	RET

