// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sein

import (
	"errors"
	"reflect"

	"github.com/lemon4ksan/sein/internal/binder"
)

// Ingestable is implemented by compiled DTOs (e.g. generated by vortex gen) for zero-reflection, multi-source ingestion.
type Ingestable = binder.Ingestable

// IngestDTO extracts multi-source request data (Path, Query, Headers, Cookies, Auth, Net, Form, Files, Context, Body) into dest.
func IngestDTO[T any](req *Request, dest *T) error {
	adapter := newRequestAdapter(req)
	if err := binder.Ingest(adapter, dest); err != nil {
		return mapBinderError(err)
	}

	return nil
}

// ValidateRouteBinding checks at server startup that all URL path parameters declared in path
// have corresponding bindings in the DTO type T.
func ValidateRouteBinding[T any](routePath string) {
	binder.ValidateRouteBinding(reflect.TypeFor[T](), routePath)
}

type requestAdapter struct {
	req *Request
}

func newRequestAdapter(req *Request) *requestAdapter {
	return &requestAdapter{req: req}
}

func (a *requestAdapter) Param(name string) string {
	return string(a.req.Param(name))
}

func (a *requestAdapter) Query(key string) string {
	return string(a.req.Query(key))
}

func (a *requestAdapter) Header(key string) string {
	return a.req.Header(key)
}

func (a *requestAdapter) Cookie(name string) (string, error) {
	return a.req.Cookie(name)
}

func (a *requestAdapter) BearerToken() (string, bool) {
	return a.req.BearerToken()
}

func (a *requestAdapter) ClientIP() string {
	return a.req.ClientIP()
}

func (a *requestAdapter) Protocol() string {
	return a.req.Protocol()
}

func (a *requestAdapter) Scheme() string {
	return a.req.Scheme()
}

func (a *requestAdapter) Host() string {
	return a.req.Host()
}

func (a *requestAdapter) Method() string {
	return a.req.Method()
}

func (a *requestAdapter) Path() string {
	return a.req.Path()
}

func (a *requestAdapter) FormValue(key string) string {
	return a.req.FormValue(key)
}

func (a *requestAdapter) FormFile(key string) (any, error) {
	return a.req.FormFile(key)
}

func (a *requestAdapter) FormFiles(key string) ([]any, error) {
	files, err := a.req.FormFiles(key)
	if err != nil {
		return nil, err
	}

	res := make([]any, len(files))
	for i, f := range files {
		res[i] = f
	}

	return res, nil
}

func (a *requestAdapter) Body() []byte {
	return a.req.Body()
}

func (a *requestAdapter) BindJSON(dest any) error {
	return a.req.BindJSON(dest)
}

func (a *requestAdapter) GetContext(typ reflect.Type) (any, bool) {
	for i := range a.req.slotCount {
		if a.req.slots[i].typ == typ {
			return a.req.slots[i].val, true
		}
	}

	if a.req.overflow != nil {
		val, ok := a.req.overflow[typ]
		return val, ok
	}

	return nil, false
}

func (a *requestAdapter) RawURLQuery() map[string][]string {
	if a.req.raw != nil && a.req.raw.URL != nil {
		return a.req.raw.URL.Query()
	}

	return nil
}

func mapBinderError(err error) error {
	if err == nil {
		return nil
	}

	if domainErr, ok := errors.AsType[DomainError](err); ok {
		return domainErr
	}

	if valErr, ok := errors.AsType[binder.ValidationError](err); ok {
		return ErrValidationFailed.WithMessage(valErr.Message)
	}

	if scalarErr, ok := errors.AsType[binder.ScalarError](err); ok {
		switch scalarErr.Source {
		case binder.SourcePath:
			return ErrInvalidPathParam.WithDetail("param", scalarErr.Key).WithCause(scalarErr.Cause)
		case binder.SourceQuery:
			return ErrInvalidQueryParam.WithDetail("param", scalarErr.Key).WithCause(scalarErr.Cause)
		case binder.SourceHeader:
			return ErrInvalidHeader.WithDetail("header", scalarErr.Key).WithCause(scalarErr.Cause)
		case binder.SourceCookie:
			return ErrInvalidCookie.WithDetail("cookie", scalarErr.Key).WithCause(scalarErr.Cause)
		default:
			return ErrInvalidPathParam.WithDetail("key", scalarErr.Key).WithCause(scalarErr.Cause)
		}
	}

	switch {
	case errors.Is(err, binder.ErrMissingPathParam):
		return ErrMissingPathParam
	case errors.Is(err, binder.ErrMissingQueryParam):
		return ErrMissingQueryParam
	case errors.Is(err, binder.ErrMissingHeader):
		return ErrMissingHeader
	case errors.Is(err, binder.ErrMissingCookie):
		return ErrMissingCookie
	case errors.Is(err, binder.ErrMissingBearerToken):
		return ErrMissingBearerToken
	case errors.Is(err, binder.ErrMissingContext):
		return ErrMissingContext
	case errors.Is(err, binder.ErrEmptyRequestBody):
		return ErrEmptyRequestBody
	}

	return ErrBadRequest(err.Error(), err)
}
