// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sein

import (
	"errors"
	"reflect"
	"strconv"
	"sync"
	"unsafe"
)

// Ingestable is implemented by compiled DTOs (e.g. generated by vortex gen) for zero-reflection, multi-source ingestion.
type Ingestable interface {
	Ingest(req *Request) error
}

type paramSource uint8

const (
	sourcePath paramSource = iota
	sourceQuery
	sourceHeader
	sourceCookie
)

type fieldBinding struct {
	offset uintptr
	kind   reflect.Kind
	source paramSource
	key    string
}

type structDescriptor struct {
	hasBodyFields bool
	bindings      []fieldBinding
}

var descriptorCache sync.Map // map[reflect.Type]*structDescriptor

func getDescriptor(typ reflect.Type) *structDescriptor {
	if typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	if typ.Kind() != reflect.Struct {
		return nil
	}

	if d, ok := descriptorCache.Load(typ); ok {
		return d.(*structDescriptor)
	}

	desc := &structDescriptor{}
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		if !field.IsExported() {
			continue
		}

		if key, ok := field.Tag.Lookup("path"); ok {
			desc.bindings = append(desc.bindings, fieldBinding{
				offset: field.Offset,
				kind:   field.Type.Kind(),
				source: sourcePath,
				key:    key,
			})
		} else if key, ok := field.Tag.Lookup("param"); ok {
			desc.bindings = append(desc.bindings, fieldBinding{
				offset: field.Offset,
				kind:   field.Type.Kind(),
				source: sourcePath,
				key:    key,
			})
		} else if key, ok := field.Tag.Lookup("query"); ok {
			desc.bindings = append(desc.bindings, fieldBinding{
				offset: field.Offset,
				kind:   field.Type.Kind(),
				source: sourceQuery,
				key:    key,
			})
		} else if key, ok := field.Tag.Lookup("header"); ok {
			desc.bindings = append(desc.bindings, fieldBinding{
				offset: field.Offset,
				kind:   field.Type.Kind(),
				source: sourceHeader,
				key:    key,
			})
		} else if key, ok := field.Tag.Lookup("cookie"); ok {
			desc.bindings = append(desc.bindings, fieldBinding{
				offset: field.Offset,
				kind:   field.Type.Kind(),
				source: sourceCookie,
				key:    key,
			})
		}

		if _, ok := field.Tag.Lookup("json"); ok {
			desc.hasBodyFields = true
		}
	}

	descriptorCache.Store(typ, desc)
	return desc
}

// IngestDTO extracts multi-source request data (Path, Query, Headers, Body) into dest.
func IngestDTO[T any](req *Request, dest *T) error {
	// 1. Check Ingestable interface (vortex gen compiled fast-path)
	if ing, ok := any(dest).(Ingestable); ok {
		if err := ing.Ingest(req); err != nil {
			return err
		}
		return runValidation(dest)
	}

	typ := reflect.TypeFor[T]()
	desc := getDescriptor(typ)
	if desc == nil {
		if len(req.Body()) > 0 {
			if err := req.BindJSON(dest); err != nil {
				return err
			}
		}
		return runValidation(dest)
	}

	ptr := unsafe.Pointer(dest)

	// 2. Extract Path, Query, Header, Cookie bindings
	for _, b := range desc.bindings {
		var rawVal string
		switch b.source {
		case sourcePath:
			rawVal = string(req.Param(b.key))
			if rawVal == "" {
				return ErrMissingPathParam.WithDetail("param", b.key)
			}
		case sourceQuery:
			rawVal = string(req.Query(b.key))
			if rawVal == "" {
				continue // optional query param
			}
		case sourceHeader:
			rawVal = req.Header(b.key)
			if rawVal == "" {
				continue // optional header
			}
		case sourceCookie:
			c, err := req.Cookie(b.key)
			if err != nil || c == "" {
				continue
			}
			rawVal = c
		}

		fieldPtr := unsafe.Pointer(uintptr(ptr) + b.offset)
		if err := assignScalar(fieldPtr, b.kind, rawVal); err != nil {
			return err
		}
	}

	// 3. Extract JSON body if fields are defined
	if desc.hasBodyFields && len(req.Body()) > 0 {
		if err := req.BindJSON(dest); err != nil {
			return err
		}
	}

	return runValidation(dest)
}

func runValidation(dest any) error {
	if v, ok := dest.(Validatable); ok {
		if err := v.Validate(); err != nil {
			var domainErr DomainError
			if errors.As(err, &domainErr) {
				return domainErr
			}
			return ErrValidationFailed.WithMessage(err.Error())
		}
	}
	return nil
}

func assignScalar(ptr unsafe.Pointer, kind reflect.Kind, s string) error {
	switch kind {
	case reflect.String:
		*(*string)(ptr) = s
	case reflect.Uint64, reflect.Uint:
		v, err := strconv.ParseUint(s, 10, 64)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*uint64)(ptr) = v
	case reflect.Uint32:
		v, err := strconv.ParseUint(s, 10, 32)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*uint32)(ptr) = uint32(v)
	case reflect.Uint16:
		v, err := strconv.ParseUint(s, 10, 16)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*uint16)(ptr) = uint16(v)
	case reflect.Uint8:
		v, err := strconv.ParseUint(s, 10, 8)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*uint8)(ptr) = uint8(v)
	case reflect.Int64, reflect.Int:
		v, err := strconv.ParseInt(s, 10, 64)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*int64)(ptr) = v
	case reflect.Int32:
		v, err := strconv.ParseInt(s, 10, 32)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*int32)(ptr) = int32(v)
	case reflect.Int16:
		v, err := strconv.ParseInt(s, 10, 16)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*int16)(ptr) = int16(v)
	case reflect.Int8:
		v, err := strconv.ParseInt(s, 10, 8)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*int8)(ptr) = int8(v)
	case reflect.Bool:
		v, err := strconv.ParseBool(s)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*bool)(ptr) = v
	case reflect.Float64:
		v, err := strconv.ParseFloat(s, 64)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*float64)(ptr) = v
	case reflect.Float32:
		v, err := strconv.ParseFloat(s, 32)
		if err != nil {
			return ErrInvalidPathParam.WithCause(err)
		}
		*(*float32)(ptr) = float32(v)
	}
	return nil
}
