// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sein

import (
	"encoding"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode"
	"unsafe"
)

// Ingestable is implemented by compiled DTOs (e.g. generated by vortex gen) for zero-reflection, multi-source ingestion.
type Ingestable interface {
	Ingest(req *Request) error
}

type paramSource uint8

const (
	sourcePath paramSource = iota
	sourceQuery
	sourceHeader
	sourceCookie
	sourceAuth
	sourceNet
	sourceForm
	sourceFile
	sourceFiles
	sourceBodyRaw
	sourceBodyString
	sourceContext
)

type fieldBinding struct {
	offset        uintptr
	kind          reflect.Kind
	fieldType     reflect.Type
	source        paramSource
	key           string
	required      bool
	defaultValue  string
	isPtr         bool
	elemKind      reflect.Kind
	isSlice       bool
	sliceElemKind reflect.Kind

	// Sanitizers / Transforms
	trim        bool
	lower       bool
	upper       bool
	singleSpace bool
	digitsOnly  bool

	// Constraints / Validation
	hasMin   bool
	minVal   float64
	hasMax   bool
	maxVal   float64
	hasLen   bool
	lenVal   int
	enumVals []string
	isEmail  bool
}

type structDescriptor struct {
	hasBodyFields bool
	bindings      []fieldBinding
}

var descriptorCache sync.Map // map[reflect.Type]*structDescriptor

// parseTagOptions extracts key and modifier flags like "default=xyz", "required", "trim", "lower", "upper", "min=1", "max=100", "enum=a|b".
func parseTagOptions(tagStr string, binding *fieldBinding) {
	parts := strings.Split(tagStr, ",")
	binding.key = strings.TrimSpace(parts[0])

	for _, part := range parts[1:] {
		part = strings.TrimSpace(part)
		switch {
		case part == "required":
			binding.required = true
		case strings.HasPrefix(part, "default="):
			binding.defaultValue = strings.TrimPrefix(part, "default=")
		case part == "trim":
			binding.trim = true
		case part == "lower":
			binding.lower = true
		case part == "upper":
			binding.upper = true
		case part == "single_space" || part == "squish":
			binding.singleSpace = true
		case part == "digits_only":
			binding.digitsOnly = true
		case part == "email":
			binding.isEmail = true
		case strings.HasPrefix(part, "min="):
			if v, err := strconv.ParseFloat(strings.TrimPrefix(part, "min="), 64); err == nil {
				binding.hasMin = true
				binding.minVal = v
			}
		case strings.HasPrefix(part, "max="):
			if v, err := strconv.ParseFloat(strings.TrimPrefix(part, "max="), 64); err == nil {
				binding.hasMax = true
				binding.maxVal = v
			}
		case strings.HasPrefix(part, "len="):
			if v, err := strconv.Atoi(strings.TrimPrefix(part, "len=")); err == nil {
				binding.hasLen = true
				binding.lenVal = v
			}
		case strings.HasPrefix(part, "enum="):
			binding.enumVals = strings.Split(strings.TrimPrefix(part, "enum="), "|")
		}
	}
}

func getDescriptor(typ reflect.Type) *structDescriptor {
	if typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	if typ.Kind() != reflect.Struct {
		return nil
	}

	if d, ok := descriptorCache.Load(typ); ok {
		return d.(*structDescriptor)
	}

	desc := &structDescriptor{}
	for field := range typ.Fields() {
		field := field
		if !field.IsExported() {
			continue
		}

		ft := field.Type
		isPtr := ft.Kind() == reflect.Pointer
		elemKind := ft.Kind()
		if isPtr {
			elemKind = ft.Elem().Kind()
		}

		isSlice := ft.Kind() == reflect.Slice && ft != netIPType && ft != reflect.TypeFor[[]byte]()
		sliceElemKind := reflect.Invalid
		if isSlice {
			sliceElemKind = ft.Elem().Kind()
		}

		b := fieldBinding{
			offset:        field.Offset,
			kind:          field.Type.Kind(),
			fieldType:     field.Type,
			isPtr:         isPtr,
			elemKind:      elemKind,
			isSlice:       isSlice,
			sliceElemKind: sliceElemKind,
		}

		var matched bool

		if tag, ok := field.Tag.Lookup("path"); ok {
			b.source = sourcePath
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = field.Name
			}
			b.required = true
			matched = true
		} else if tag, ok := field.Tag.Lookup("param"); ok {
			b.source = sourcePath
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = field.Name
			}
			b.required = true
			matched = true
		} else if tag, ok := field.Tag.Lookup("query"); ok {
			b.source = sourceQuery
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = field.Name
			}
			matched = true
		} else if tag, ok := field.Tag.Lookup("header"); ok {
			b.source = sourceHeader
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = field.Name
			}
			matched = true
		} else if tag, ok := field.Tag.Lookup("cookie"); ok {
			b.source = sourceCookie
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = field.Name
			}
			matched = true
		} else if tag, ok := field.Tag.Lookup("auth"); ok {
			b.source = sourceAuth
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = "bearer"
			}
			matched = true
		} else if tag, ok := field.Tag.Lookup("net"); ok {
			b.source = sourceNet
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = "ip"
			}
			matched = true
		} else if tag, ok := field.Tag.Lookup("form"); ok {
			b.source = sourceForm
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = field.Name
			}
			matched = true
		} else if tag, ok := field.Tag.Lookup("file"); ok {
			b.source = sourceFile
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = field.Name
			}
			matched = true
		} else if tag, ok := field.Tag.Lookup("files"); ok {
			b.source = sourceFiles
			parseTagOptions(tag, &b)
			if b.key == "" {
				b.key = field.Name
			}
			matched = true
		} else if tag, ok := field.Tag.Lookup("body"); ok {
			parseTagOptions(tag, &b)
			if b.key == "raw" || b.fieldType == reflect.TypeFor[[]byte]() {
				b.source = sourceBodyRaw
			} else {
				b.source = sourceBodyString
			}
			matched = true
		} else if tag, ok := field.Tag.Lookup("ctx"); ok {
			b.source = sourceContext
			parseTagOptions(tag, &b)
			matched = true
		} else if tag, ok := field.Tag.Lookup("context"); ok {
			b.source = sourceContext
			parseTagOptions(tag, &b)
			matched = true
		}

		if matched {
			desc.bindings = append(desc.bindings, b)
		}

		if _, ok := field.Tag.Lookup("json"); ok {
			desc.hasBodyFields = true
		}
	}

	descriptorCache.Store(typ, desc)
	return desc
}

// IngestDTO extracts multi-source request data (Path, Query, Headers, Cookies, Auth, Net, Form, Files, Context, Body) into dest.
func IngestDTO[T any](req *Request, dest *T) error {
	// 1. Check Ingestable interface (vortex gen fast-path)
	if ing, ok := any(dest).(Ingestable); ok {
		if err := ing.Ingest(req); err != nil {
			return err
		}
		return runValidation(dest)
	}

	typ := reflect.TypeFor[T]()
	desc := getDescriptor(typ)
	if desc == nil {
		if len(req.Body()) > 0 {
			if err := req.BindJSON(dest); err != nil {
				return err
			}
		}
		return runValidation(dest)
	}

	ptr := unsafe.Pointer(dest)

	// 2. Extract multi-source bindings
	for _, b := range desc.bindings {
		fieldPtr := unsafe.Add(ptr, b.offset)

		switch b.source {
		case sourceContext:
			if err := injectContextField(req, ptr, b); err != nil {
				return err
			}
			continue

		case sourceFile:
			file, err := req.FormFile(b.key)
			if err != nil || file == nil {
				if b.required {
					return ErrBadRequest(fmt.Sprintf("required file %q is missing", b.key))
				}
				continue
			}
			*(*(*File))(fieldPtr) = file
			continue

		case sourceFiles:
			files, err := req.FormFiles(b.key)
			if err != nil || len(files) == 0 {
				if b.required {
					return ErrBadRequest(fmt.Sprintf("required files %q are missing", b.key))
				}
				continue
			}
			*(*[]*File)(fieldPtr) = files
			continue

		case sourceBodyRaw:
			data := req.Body()
			if len(data) == 0 && b.required {
				return ErrEmptyRequestBody
			}
			*(*[]byte)(fieldPtr) = data
			continue

		case sourceBodyString:
			data := req.Body()
			if len(data) == 0 && b.required {
				return ErrEmptyRequestBody
			}
			*(*string)(fieldPtr) = string(data)
			continue
		}

		var (
			rawVal  string
			present bool
		)

		switch b.source {
		case sourcePath:
			rawVal = string(req.Param(b.key))
			present = rawVal != ""
			if !present {
				if b.defaultValue != "" {
					rawVal = b.defaultValue
					present = true
				} else {
					return ErrMissingPathParam.WithDetail("param", b.key)
				}
			}

		case sourceQuery:
			rawVal = string(req.Query(b.key))
			present = rawVal != ""
			if !present {
				if b.defaultValue != "" {
					rawVal = b.defaultValue
					present = true
				} else if b.required {
					return ErrMissingQueryParam.WithDetail("param", b.key)
				}
			}

		case sourceHeader:
			rawVal = req.Header(b.key)
			present = rawVal != ""
			if !present {
				if b.defaultValue != "" {
					rawVal = b.defaultValue
					present = true
				} else if b.required {
					return ErrMissingHeader.WithDetail("header", b.key)
				}
			}

		case sourceCookie:
			c, err := req.Cookie(b.key)
			present = err == nil && c != ""
			if present {
				rawVal = c
			} else {
				if b.defaultValue != "" {
					rawVal = b.defaultValue
					present = true
				} else if b.required {
					return ErrMissingCookie.WithDetail("cookie", b.key)
				}
			}

		case sourceAuth:
			if strings.EqualFold(b.key, "bearer") {
				token, ok := req.BearerToken()
				if ok {
					rawVal = token
					present = true
				} else if b.required {
					return ErrMissingBearerToken
				}
			}

		case sourceNet:
			switch strings.ToLower(b.key) {
			case "ip", "client_ip", "remote_ip":
				rawVal = req.ClientIP()
				present = rawVal != ""
			case "proto", "protocol":
				rawVal = req.Protocol()
				present = rawVal != ""
			case "scheme":
				rawVal = req.Scheme()
				present = rawVal != ""
			case "host":
				rawVal = req.Host()
				present = rawVal != ""
			case "method":
				rawVal = req.Method()
				present = rawVal != ""
			case "path":
				rawVal = req.Path()
				present = rawVal != ""
			}

		case sourceForm:
			rawVal = req.FormValue(b.key)
			present = rawVal != ""
			if !present {
				if b.defaultValue != "" {
					rawVal = b.defaultValue
					present = true
				} else if b.required {
					return ErrBadRequest(fmt.Sprintf("required form field %q is missing", b.key))
				}
			}
		}

		if !present {
			continue
		}

		// Apply string sanitizers / transforms
		rawVal = applyTransforms(rawVal, b)

		// Apply constraints / validations
		if err := validateConstraints(rawVal, b); err != nil {
			return err
		}

		if b.isSlice {
			if err := assignSlice(req, fieldPtr, b, rawVal); err != nil {
				return err
			}
			continue
		}

		targetKind := b.kind
		targetPtr := fieldPtr
		targetType := b.fieldType

		if b.isPtr {
			targetKind = b.elemKind
			targetType = b.fieldType.Elem()
			// Allocate heap value for pointer
			valPtr := reflect.New(targetType).UnsafePointer()
			*(*unsafe.Pointer)(fieldPtr) = valPtr
			targetPtr = valPtr
		}

		if err := assignScalar(targetPtr, targetKind, targetType, rawVal, b.source, b.key); err != nil {
			return err
		}
	}

	// 3. Extract JSON body if fields are defined
	if desc.hasBodyFields && len(req.Body()) > 0 {
		if err := req.BindJSON(dest); err != nil {
			return err
		}
	}

	return runValidation(dest)
}

func applyTransforms(s string, b fieldBinding) string {
	if b.trim {
		s = strings.TrimSpace(s)
	}
	if b.lower {
		s = strings.ToLower(s)
	}
	if b.upper {
		s = strings.ToUpper(s)
	}
	if b.singleSpace {
		var buf strings.Builder
		inSpace := false
		for _, r := range s {
			if unicode.IsSpace(r) {
				if !inSpace {
					buf.WriteRune(' ')
					inSpace = true
				}
			} else {
				buf.WriteRune(r)
				inSpace = false
			}
		}
		s = strings.TrimSpace(buf.String())
	}
	if b.digitsOnly {
		var buf strings.Builder
		for _, r := range s {
			if unicode.IsDigit(r) {
				buf.WriteRune(r)
			}
		}
		s = buf.String()
	}
	return s
}

func validateConstraints(s string, b fieldBinding) error {
	if b.hasLen && len(s) != b.lenVal {
		return ErrValidationFailed.WithMessage(fmt.Sprintf("%s length must be exactly %d", b.key, b.lenVal))
	}

	if b.isEmail && s != "" {
		if !strings.Contains(s, "@") || !strings.Contains(s, ".") {
			return ErrValidationFailed.WithMessage(fmt.Sprintf("%s must be a valid email address", b.key))
		}
	}

	if len(b.enumVals) > 0 && s != "" {
		found := false
		for _, ev := range b.enumVals {
			if strings.EqualFold(s, ev) {
				found = true
				break
			}
		}
		if !found {
			return ErrValidationFailed.WithMessage(fmt.Sprintf("%s must be one of [%s], got %q", b.key, strings.Join(b.enumVals, ", "), s))
		}
	}

	if (b.hasMin || b.hasMax) && (b.kind == reflect.String || (b.isPtr && b.elemKind == reflect.String)) {
		strLen := float64(len(s))
		if b.hasMin && strLen < b.minVal {
			return ErrValidationFailed.WithMessage(fmt.Sprintf("%s length must be at least %v", b.key, b.minVal))
		}
		if b.hasMax && strLen > b.maxVal {
			return ErrValidationFailed.WithMessage(fmt.Sprintf("%s length must be at most %v", b.key, b.maxVal))
		}
	}

	return nil
}

func injectContextField(req *Request, structPtr unsafe.Pointer, b fieldBinding) error {
	targetTyp := b.fieldType

	// Linear scan through flat [8]contextSlot in L1 CPU cache
	for i := range req.slotCount {
		if req.slots[i].typ == targetTyp {
			val := req.slots[i].val
			fieldPtr := unsafe.Pointer(uintptr(structPtr) + b.offset)
			reflect.NewAt(targetTyp, fieldPtr).Elem().Set(reflect.ValueOf(val))
			return nil
		}
	}

	if req.overflow != nil {
		if val, ok := req.overflow[targetTyp]; ok {
			fieldPtr := unsafe.Pointer(uintptr(structPtr) + b.offset)
			reflect.NewAt(targetTyp, fieldPtr).Elem().Set(reflect.ValueOf(val))
			return nil
		}
	}

	if b.required {
		return ErrMissingContext.WithDetail("type", targetTyp.String())
	}
	return nil
}

func assignSlice(req *Request, fieldPtr unsafe.Pointer, b fieldBinding, initialVal string) error {
	var vals []string
	if b.source == sourceQuery && req.raw != nil && req.raw.URL != nil {
		q := req.raw.URL.Query()
		if sliceVals, ok := q[b.key]; ok && len(sliceVals) > 0 {
			for _, sv := range sliceVals {
				for _, item := range strings.Split(sv, ",") {
					if item = strings.TrimSpace(item); item != "" {
						vals = append(vals, item)
					}
				}
			}
		}
	}

	if len(vals) == 0 && initialVal != "" {
		for _, item := range strings.Split(initialVal, ",") {
			if item = strings.TrimSpace(item); item != "" {
				vals = append(vals, item)
			}
		}
	}

	if b.hasMin && float64(len(vals)) < b.minVal {
		return ErrValidationFailed.WithMessage(fmt.Sprintf("%s slice length must be at least %v", b.key, b.minVal))
	}
	if b.hasMax && float64(len(vals)) > b.maxVal {
		return ErrValidationFailed.WithMessage(fmt.Sprintf("%s slice length must be at most %v", b.key, b.maxVal))
	}

	sliceVal := reflect.MakeSlice(b.fieldType, len(vals), len(vals))
	for i, v := range vals {
		v = applyTransforms(v, b)
		elemPtr := sliceVal.Index(i).Addr().UnsafePointer()
		elemType := b.fieldType.Elem()
		if err := assignScalar(elemPtr, b.sliceElemKind, elemType, v, b.source, b.key); err != nil {
			return err
		}
	}

	reflect.NewAt(b.fieldType, fieldPtr).Elem().Set(sliceVal)
	return nil
}

func runValidation(dest any) error {
	if v, ok := dest.(Validatable); ok {
		if err := v.Validate(); err != nil {
			var domainErr DomainError
			if errors.As(err, &domainErr) {
				return domainErr
			}
			return ErrValidationFailed.WithMessage(err.Error())
		}
	}
	return nil
}

func formatSourceError(src paramSource, key string, err error) error {
	switch src {
	case sourcePath:
		return ErrInvalidPathParam.WithDetail("param", key).WithCause(err)
	case sourceQuery:
		return ErrInvalidQueryParam.WithDetail("param", key).WithCause(err)
	case sourceHeader:
		return ErrInvalidHeader.WithDetail("header", key).WithCause(err)
	case sourceCookie:
		return ErrInvalidCookie.WithDetail("cookie", key).WithCause(err)
	default:
		return ErrInvalidPathParam.WithDetail("key", key).WithCause(err)
	}
}

var (
	textUnmarshalerType = reflect.TypeFor[encoding.TextUnmarshaler]()
	timeType            = reflect.TypeFor[time.Time]()
	durationType        = reflect.TypeFor[time.Duration]()
	netIPType           = reflect.TypeFor[net.IP]()
	netipAddrType       = reflect.TypeFor[netip.Addr]()
)

func assignScalar(ptr unsafe.Pointer, kind reflect.Kind, typ reflect.Type, s string, src paramSource, key string) error {
	// 1. Check custom encoding.TextUnmarshaler
	if typ.Implements(textUnmarshalerType) {
		val := reflect.NewAt(typ, ptr).Interface().(encoding.TextUnmarshaler)
		if err := val.UnmarshalText([]byte(s)); err != nil {
			return formatSourceError(src, key, err)
		}
		return nil
	}
	if reflect.PointerTo(typ).Implements(textUnmarshalerType) {
		val := reflect.NewAt(typ, ptr).Interface().(encoding.TextUnmarshaler)
		if err := val.UnmarshalText([]byte(s)); err != nil {
			return formatSourceError(src, key, err)
		}
		return nil
	}

	// 2. Check special stdlib types (time.Time, time.Duration, net.IP, netip.Addr)
	switch typ {
	case timeType:
		t, err := parseTime(s)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*time.Time)(ptr) = t
		return nil

	case durationType:
		d, err := time.ParseDuration(s)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*time.Duration)(ptr) = d
		return nil

	case netIPType:
		ip := net.ParseIP(s)
		if ip == nil {
			return formatSourceError(src, key, errors.New("invalid IP address"))
		}
		*(*net.IP)(ptr) = ip
		return nil

	case netipAddrType:
		addr, err := netip.ParseAddr(s)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*netip.Addr)(ptr) = addr
		return nil
	}

	// 3. Built-in scalar kinds
	switch kind {
	case reflect.String:
		*(*string)(ptr) = s

	case reflect.Uint64, reflect.Uint:
		v, err := strconv.ParseUint(s, 10, 64)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*uint64)(ptr) = v

	case reflect.Uint32:
		v, err := strconv.ParseUint(s, 10, 32)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*uint32)(ptr) = uint32(v)

	case reflect.Uint16:
		v, err := strconv.ParseUint(s, 10, 16)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*uint16)(ptr) = uint16(v)

	case reflect.Uint8:
		v, err := strconv.ParseUint(s, 10, 8)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*uint8)(ptr) = uint8(v)

	case reflect.Int64:
		v, err := strconv.ParseInt(s, 10, 64)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*int64)(ptr) = v

	case reflect.Int:
		v, err := strconv.ParseInt(s, 10, 64)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*int)(ptr) = int(v)

	case reflect.Int32:
		v, err := strconv.ParseInt(s, 10, 32)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*int32)(ptr) = int32(v)

	case reflect.Int16:
		v, err := strconv.ParseInt(s, 10, 16)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*int16)(ptr) = int16(v)

	case reflect.Int8:
		v, err := strconv.ParseInt(s, 10, 8)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*int8)(ptr) = int8(v)

	case reflect.Bool:
		v, err := parseCustomBool(s)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*bool)(ptr) = v

	case reflect.Float64:
		v, err := strconv.ParseFloat(s, 64)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*float64)(ptr) = v

	case reflect.Float32:
		v, err := strconv.ParseFloat(s, 32)
		if err != nil {
			return formatSourceError(src, key, err)
		}
		*(*float32)(ptr) = float32(v)
	}
	return nil
}

func parseTime(s string) (time.Time, error) {
	// Try RFC 3339 / ISO 8601
	if t, err := time.Parse(time.RFC3339Nano, s); err == nil {
		return t, nil
	}
	if t, err := time.Parse(time.RFC3339, s); err == nil {
		return t, nil
	}
	// Try Date-only
	if t, err := time.Parse(time.DateOnly, s); err == nil {
		return t, nil
	}
	// Try Unix timestamp (seconds or milliseconds)
	if n, err := strconv.ParseInt(s, 10, 64); err == nil {
		if n > 1e11 {
			return time.UnixMilli(n), nil
		}
		return time.Unix(n, 0), nil
	}
	return time.Time{}, errors.New("invalid date/time format")
}

func parseCustomBool(s string) (bool, error) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "1", "t", "true", "yes", "y", "on":
		return true, nil
	case "0", "f", "false", "no", "n", "off", "":
		return false, nil
	default:
		return false, strconv.ErrSyntax
	}
}

// ValidateRouteBinding checks at server startup that all URL path parameters declared in path
// have corresponding bindings in the DTO type T.
func ValidateRouteBinding[T any](routePath string) {
	typ := reflect.TypeFor[T]()
	if typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	if typ.Kind() != reflect.Struct {
		return
	}

	// Extract path variables: e.g. /users/:user_id/posts/:post_id -> ["user_id", "post_id"]
	var pathVars []string
	for _, seg := range strings.Split(routePath, "/") {
		if strings.HasPrefix(seg, ":") {
			pathVars = append(pathVars, strings.TrimPrefix(seg, ":"))
		}
	}

	if len(pathVars) == 0 {
		return
	}

	desc := getDescriptor(typ)
	if desc == nil {
		panic(fmt.Sprintf("sein: route %q declares path params %v, but DTO %s is not a struct", routePath, pathVars, typ.Name()))
	}

	boundKeys := make(map[string]bool)
	for _, b := range desc.bindings {
		if b.source == sourcePath {
			boundKeys[b.key] = true
		}
	}

	for _, pv := range pathVars {
		if !boundKeys[pv] {
			panic(fmt.Sprintf("sein: route %q declares path param :%s, but DTO %s has no matching field with `path:%q` tag",
				routePath, pv, typ.Name(), pv))
		}
	}
}
