// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package binder

import "reflect"

// Ingestable is implemented by compiled DTOs (e.g. generated by vortex gen) for zero-reflection, multi-source ingestion.
type Ingestable interface {
	IngestAny(req RequestView) error
}

// Validatable is implemented by DTOs that provide custom domain validation rules.
type Validatable interface {
	Validate() error
}

// RequestView is the decoupled read-only interface required by the binder engine.
type RequestView interface {
	Param(name string) string
	Query(key string) string
	Header(key string) string
	Cookie(name string) (string, error)
	BearerToken() (string, bool)
	ClientIP() string
	Protocol() string
	Scheme() string
	Host() string
	Method() string
	Path() string
	FormValue(key string) string
	FormFile(key string) (any, error)
	FormFiles(key string) ([]any, error)
	Body() []byte
	BindJSON(dest any) error
	GetContext(typ reflect.Type) (any, bool)
	RawURLQuery() map[string][]string
}
