// Code generated by c2plan9. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func h2_frame_header_pack
TEXT ·h2_frame_header_pack(SB), NOSPLIT, $0-56
	MOVQ arg0+0(FP), DI
	MOVQ arg1+8(FP), SI
	MOVQ arg2+16(FP), DX
	MOVQ arg3+24(FP), CX
	MOVQ arg4+32(FP), R8
	MOVQ arg5+40(FP), R9

	SHLQ $0x28, SI
	MOVBLZX DL, AX
	SHLQ $0x20, AX
	ORQ SI, AX
	SHLL $0x18, CX
	ORQ AX, CX
	MOVL R8, AX
	SHRL $0x8, AX
	ANDL $0x7fffff, AX
	ORQ CX, AX
	BSWAPQ AX
	MOVQ AX, 0(DI)
	MOVB R8B, 0x8(DI)
	MOVQ AX, ret+48(FP)
	RET

// func h2_frame_header_unpack
TEXT ·h2_frame_header_unpack(SB), NOSPLIT, $0-56
	MOVQ arg0+0(FP), DI
	MOVQ arg1+8(FP), SI
	MOVQ arg2+16(FP), DX
	MOVQ arg3+24(FP), CX
	MOVQ arg4+32(FP), R8
	MOVQ arg5+40(FP), R9

	MOVQ 0(DI), AX
	BSWAPQ AX
	MOVQ AX, R9
	SHRQ $0x28, R9
	MOVQ R9, 0(SI)
	MOVQ AX, SI
	SHRQ $0x20, SI
	MOVBLZX SI, SI
	MOVQ SI, 0(DX)
	MOVL AX, DX
	SHRL $0x18, DX
	MOVQ DX, 0(CX)
	SHLL $0x8, AX
	MOVBLZX 0x8(DI), CX
	ANDL $0x7fffff00, AX
	ORQ CX, AX
	MOVQ AX, 0(R8)
	MOVQ AX, ret+48(FP)
	RET

