// Code generated by c2plan9. DO NOT EDIT.

//go:build arm64 && !purego

#include "textflag.h"

// func h2_frame_header_pack
TEXT ·h2_frame_header_pack(SB), NOSPLIT, $0-72
	MOVD arg0+0(FP), R0
	MOVD arg1+8(FP), R1
	MOVD arg2+16(FP), R2
	MOVD arg3+24(FP), R3
	MOVD arg4+32(FP), R4
	MOVD arg5+40(FP), R5
	MOVD arg6+48(FP), R6
	MOVD arg7+56(FP), R7

	LSL $40, R1, R8
	MOVB R4, 8(R0)
	BFI $32, R2, $8, R8
	BFI $24, R3, $8, R8
	BFXIL $8, R4, $23, R8
	REV R8, R8
	MOVD R8, (R0)
	MOVD R0, ret+64(FP)
	RET

// func h2_frame_header_unpack
TEXT ·h2_frame_header_unpack(SB), NOSPLIT, $0-72
	MOVD arg0+0(FP), R0
	MOVD arg1+8(FP), R1
	MOVD arg2+16(FP), R2
	MOVD arg3+24(FP), R3
	MOVD arg4+32(FP), R4
	MOVD arg5+40(FP), R5
	MOVD arg6+48(FP), R6
	MOVD arg7+56(FP), R7

	MOVD (R0), R8
	REV R8, R8
	LSR $40, R8, R9
	UBFX $32, R8, $8, R10
	MOVD R9, (R1)
	LSRW $24, R8, R9
	MOVD R10, (R2)
	MOVD R9, (R3)
	MOVBU 8(R0), R9
	BFI $8, R8, $23, R9
	MOVD R9, (R4)
	MOVD R0, ret+64(FP)
	RET

