// Code generated by c2plan9. DO NOT EDIT.

//go:build arm64 && !purego

package h2engine

import "unsafe"

var _ = unsafe.Pointer(nil)

//go:noescape
func hpack_huffman_encode_count(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64, arg6 uint64, arg7 uint64) uint64

//go:noescape
func hpack_huffman_encode(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64, arg6 uint64, arg7 uint64) uint64

//go:noescape
func hpack_huffman_decode(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64, arg6 uint64, arg7 uint64) uint64
