// Code generated by c2plan9. DO NOT EDIT.

//go:build arm64 && !purego

#include "textflag.h"

// func quic_hp_mask_apply
TEXT ·quic_hp_mask_apply(SB), NOSPLIT, $0-72
	MOVD arg0+0(FP), R0
	MOVD arg1+8(FP), R1
	MOVD arg2+16(FP), R2
	MOVD arg3+24(FP), R3
	MOVD arg4+32(FP), R4
	MOVD arg5+40(FP), R5
	MOVD arg6+48(FP), R6
	MOVD arg7+56(FP), R7

	CMP $0, R4
	MOVBU (R0), R8
	MOVW $15, R9
	MOVW $31, R10
	CSELW EQ, R10, R9, R9
	MOVBU (R1), R10
	CMP $3, R3
	ANDW R9, R8, R8
	EORW R10, R8, R8
	MOVB R8, (R1)
	BLS L_0040
	MOVWU 1(R0), R8
	MOVWU (R2), R9
	EORW R8, R9, R8
	MOVW R8, (R2)
	MOVD R0, ret+64(FP)
	RET
L_0040:
	CBZ R3, L_0084
	MOVBU 1(R0), R8
	MOVBU (R2), R9
	CMP $1, R3
	EORW R8, R9, R8
	MOVB R8, (R2)
	BEQ L_0084
	MOVBU 2(R0), R8
	MOVBU 1(R2), R9
	CMP $2, R3
	EORW R8, R9, R8
	MOVB R8, 1(R2)
	BEQ L_0084
	MOVBU 3(R0), R8
	MOVBU 2(R2), R9
	EORW R8, R9, R8
	MOVB R8, 2(R2)
L_0084:
	MOVD R0, ret+64(FP)
	RET

