// Code generated by c2plan9. DO NOT EDIT.

//go:build arm64 && !purego

package handshake

import "unsafe"

var _ = unsafe.Pointer(nil)

//go:noescape
func quic_hp_mask_apply(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64, arg6 uint64, arg7 uint64) uint64
