// Code generated by c2plan9. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func quic_hp_mask_apply
TEXT ·quic_hp_mask_apply(SB), NOSPLIT, $0-56
	MOVQ arg0+0(FP), DI
	MOVQ arg1+8(FP), SI
	MOVQ arg2+16(FP), DX
	MOVQ arg3+24(FP), CX
	MOVQ arg4+32(FP), R8
	MOVQ arg5+40(FP), R9

	TESTQ R8, R8
	SETEQ AL
	SHLB $0x4, AL
	ORB $0xf, AL
	ANDB 0(DI), AL
	XORB AL, 0(SI)
	CMPQ CX, $0x3
	JBE L_001b
	MOVL 0x1(DI), AX
	XORL AX, 0(DX)
	MOVQ AX, ret+48(FP)
	RET
L_001b:
	TESTQ CX, CX
	JE L_0040
	MOVBLZX 0x1(DI), AX
	XORB AL, 0(DX)
	CMPQ CX, $0x1
	JE L_0040
	MOVBLZX 0x2(DI), AX
	XORB AL, 0x1(DX)
	CMPQ CX, $0x2
	JE L_0040
	MOVBLZX 0x3(DI), AX
	XORB AL, 0x2(DX)
L_0040:
	MOVQ AX, ret+48(FP)
	RET

