// Code generated by c2plan9. DO NOT EDIT.

//go:build amd64 && !purego

package ws

import "unsafe"

var _ = unsafe.Pointer(nil)

//go:noescape
func ws_mask_xor(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64) uint64

//go:noescape
func ws_build_frame_header(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64) uint64
